dashboard/urls.py
from django.urls import path, re_path
from .views import *

app_name = 'main'
urlpatterns = [
   path('', IndexView.as_view(), name='index'),
   re_path(r'progress/(?P<p_client>\d+)', view_progress, name='view_progress')

]

ryuclient/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls', namespace='auth')),
    path('controller/', include('admin_system.urls', namespace='controller')),
    path('', include('dashboard.urls', namespace='main'))
]

dashboard/models.py
from django.contrib.auth.models import User
from django.db import models


class Project(models.Model):
    """
    A single project object
    """
    # requested user
    request_user = models.ForeignKey(User, on_delete=models.CASCADE, default=0)

    date_requested = models.DateTimeField()

    estimated_date_of_completion = models.DateTimeField(blank=True, null=True)

    milestones = models.ManyToManyField('Milestone', related_name='project_milestones', blank=True)

    project_name = models.CharField(max_length=10000)

    def __str__(self):
        """
        the string representation of this model
        """
        return f'{self.project_name} requested by: {self.request_user.username}'


class Milestone(models.Model):
    """
    Milestone
    """
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    milestone_name = models.CharField(max_length=1000)
    features = models.ManyToManyField('Feature', related_name='features', blank=True)

    def __str__(self):
        """
        the string representation of this model
        """
        return f'{self.milestone_name} is a part of: {self.project.project_name}'


class Feature(models.Model):
    """
    Feature
    """
    milestone = models.ForeignKey(Milestone, on_delete=models.CASCADE)
    feature_name = models.CharField(max_length=1000)
    completed = models.BooleanField(default=False)

    def __str__(self):
        """
        the string representation of this model
        """
        return f'{self.feature_name} is a part of: {self.milestone.milestone_name}'

dashboard/forms.py
from django import forms
from django.forms import Select

from .models import *


class ProjectCreationForm(forms.ModelForm):
    """
    Form for creating a new project
    """

    requesting_user = forms.ChoiceField(
        choices=[(u.id, u.username) for u in User.objects.filter(is_superuser=False).all()]
    )

    project_name = forms.CharField(
        widget=forms.TextInput()
    )

    class Meta:
        model = Project
        fields = ('requesting_user','project_name')
        widgets = {
            'users': Select(attrs={'class': 'select'})
        }

dashboard/views.py
from django.shortcuts import redirect
from django.shortcuts import render
from django.views import View

from dashboard.progress.project_handlers import get_project
from dashboard.requests.dashboard_requests import get_request


class IndexView(View):
    """
    Main view
    """
    template_name = 'dashboard/pages/dashboard.html'

    def get(self, request, *args, **kwargs):
        """
        Processes the get request for the main page.
        """
        if not request.user.is_authenticated:
            return redirect('auth:login')
        if request.user.is_superuser:
            return redirect('controller:index')
        return render(request, self.template_name, get_request(request))


def view_progress(request, p_client):
    """
    View progress view
    """

    # if request.user.is_superuser:
    #     return redirect(reverse('controller:update_progress', args=[project_client]))

    context = {
        'title': 'RYU | Project Details',
        'project': get_project(p_client)

    }

    return render(request, 'dashboard/pages/progress-view.html', context)

templates/dashboard/pages/dashboard.html
{% extends 'maincontent.html' %}

{% block navbar %}
    {% include 'dashboard/components/navbar.html' %}
{% endblock %}
{% load crispy_forms_tags %}

{% block maincontent %}
    <section id="header">
        <div class="row">
            <div class="col">
                <h1><strong>RYU Client System&nbsp;&nbsp;</strong><span class="badge badge-danger"
                                                                        style="font-size: 34px;">Early Alpha</span>&nbsp;&nbsp;
                </h1>
                <h3>Welcome to RYU's Client System. Here, you can check your development status for your projects. You
                    will also have the option to cancel your applications.&nbsp;</h3>
                <div class="alert alert-danger" role="alert"><span
                        style="font-size: 23px;">You must contact Ryan if you want to request or delete a project. At this point,
                you are <strong>unable</strong> to request or delete a project from this system.</span>
                </div>
                <span class="badge badge-primary" style="font-size: 32px;"></span></div>
        </div>
    </section>
    <hr>
    <div class="row">
        <div class="col">
            <h1><strong>My Active Projects</strong></h1>
            <div class="alert alert-info" role="alert"><span style="font-size: 23px;"><strong>Note:</strong>&nbsp;There are two additional blank spaces for the purposes of placeholder. These are not functional.</span>
            </div>
        </div>
    </div>
    <section id="projects">
        <div class="row">
            {% if projects %}
                {% for project in projects %}
                    <div class="col-xl-4" id='{{ project.id }}'>
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title">{{ project.project_name }}</h4>

                                <a class="btn btn-primary" role="button"
                                   href="{% url 'main:view_progress' project.id %}">View Progress</a></div>
                        </div>

                    </div>
                {% endfor %}
            {% else %}
                <div class="col-xl-4">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">No new projects!</h4>
                            <h5>You have no newly created projects for {{ request.user.username }}</h5>
                        </div>
                    </div>

                </div>
            {% endif %}
        </div>
{% endblock %}

templates/dashboard/pages/progress-view.html
{% extends 'maincontent.html' %}

{% block navbar %}
    {% include 'dashboard/components/navbar.html' %}
{% endblock %}
{% load crispy_forms_tags %}

{% block maincontent %}
    <section id="header">
        <div class="row">
            <div class="col">
                <h1><strong>RYU Client System |</strong>&nbsp;Project Proposal<strong>&nbsp;&nbsp;</strong><span
                        class="badge badge-danger" style="font-size: 34px;">Early Alpha</span>&nbsp;&nbsp;</h1>
                <h3>This page will display the project proposal, including a <strong>tenative </strong>schedule for your
                    poject.</h3><span class="badge badge-primary" style="font-size: 32px;"></span>
                <div class="alert alert-info" role="alert"><span><strong>Note: </strong>the features listed here are always subject to change.</span>
                </div>
            </div>
        </div>
    </section>
    <hr>
    <section id="project-header">
        <div class="row">
            <div class="col">
                <h1><strong>{{ project.project_name }}</strong><br></h1>
                <h3>Estimated Time of Completion: <strong>{% if not project.estimated_date_of_completion %} Unknown
                {% else %}{{ project.estimated_date_of_completion }}{% endif %}</strong></h3>

            </div>
        </div>
    </section>
    <main id="milestones">

        {% if project.milestones %}
            {% for milestone in project.milestones.all %}
                <section id="milestone_{{ milestone.id }}">
                    <div class="row">
                        <div class="col">
                            <h2><strong>{{ milestone.milestone_name }}</strong></h2>
                            <p>{{ milestone.milestone_name }} means the following <span
                                    style="text-decoration: underline;">are guaranteed</span>&nbsp;to
                                be implemented.</p>
                            {% if milestone.features %}
                                <ul class="big-list">
                                    {% for feature in milestone.features.all %}
                                        <li>{{ feature.feature_name }}{% if feature.completed %}
                                            &nbsp;
                                            <span class="badge badge-success" style="font-size: 20px;font-weight: 100">Completed</span>
                                        {% endif %}</li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                        </div>
                    </div>
                </section>
            {% endfor %}
        {% endif %}
    </main>
{% endblock %}