authentication/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

app_name = 'auth'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='auth/pages/login.html', extra_context={
        'login': 'active',
        'title': 'Login | RYU'
    })
         , name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout")
]

dashboard/urls.py
from django.urls import path, re_path
from .views import *

app_name = 'main'
urlpatterns = [
   path('', IndexView.as_view(), name='index'),
   re_path(r'progress/(?P<p_client>\d+)', view_progress, name='view_progress')

]

ryuclient/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls', namespace='auth')),
    path('controller/', include('admin_system.urls', namespace='controller')),
    path('', include('dashboard.urls', namespace='main'))
]

templates/admin_sys/components/navbar.html
<nav class="navbar navbar-dark navbar-expand-md fixed-top bg-dark navigation-clean">
    <div class="container-fluid"><a class="navbar-brand" href="{% url 'controller:index' %}">RYU&nbsp;</a>
        <button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span
                class="navbar-toggler-icon"></span></button>
        <div
                class="collapse navbar-collapse" id="navcol-1">
            <ul class="nav navbar-nav ml-auto">
                <li class="nav-item" role="presentation"><a class="nav-link {{ dashboard_admin }}"
                                                            href="{% url 'controller:index' %}">Dashboard</a></li>
                <li role="presentation" class="nav-item"><a class="nav-link" href="{% url 'admin:auth_user_add' %}">Create
                    User</a></li>
                <li role="presentation" class="nav-item">
                    <button class="btn btn-info" id="new-project" type="button"
                            data-toggle="modal" data-target="#project-creation">New Project
                    </button>
                </li>

                <li class="nav-item dropdown"><a class="dropdown-toggle nav-link" data-toggle="dropdown"
                                                 aria-expanded="false" href="#">My Account</a>
                    <div class="dropdown-menu" role="menu"><a class="dropdown-item" role="presentation"
                                                              href="{% url 'admin:index' %}">View Users</a>
                        <a class="dropdown-item" role="presentation"
                           href="{% url 'auth:logout' %}">Logout</a>
                    </div>

                </li>
            </ul>
        </div>
    </div>
</nav>

{% load crispy_forms_tags %}

<div role="dialog" tabindex="-1" class="modal fade" id="project-creation">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title"><strong>Create Project</strong></h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">×</span></button>
            </div>
            <div class="modal-body">
                {% if project_creation %}

                    <form method="post" id="newProject">
                        {% csrf_token %}
                        {{ project_creation | crispy }}
                        <div class="form-group">
                            <button class="btn btn-primary" type="submit">Submit</button>
                        </div>
                        <div id="message">

                        </div>

                    </form>
                    {% else %}
                    <div role="alert" class="alert alert-danger"><span>
                        You <span style="text-decoration: underline">cannot</span> create a project on this page.
                        <br />To create a project, you must return to the
                            <a href="{% url 'controller:index' %}">home</a> page.</span></div>
                {% endif %}

            </div>
        </div>
    </div>
</div>