authentication/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

app_name = 'auth'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='auth/pages/login.html', extra_context={
        'login': 'active',
        'title': 'Login | RYU'
    })
         , name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout")
]

dashboard/urls.py
from django.urls import path, re_path
from .views import *

app_name = 'main'
urlpatterns = [
   path('', IndexView.as_view(), name='index'),
   re_path(r'progress/(?P<p_client>\d+)', view_progress, name='view_progress')

]

ryuclient/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls', namespace='auth')),
    path('controller/', include('admin_system.urls', namespace='controller')),
    path('', include('dashboard.urls', namespace='main'))
]

dashboard/models.py
from django.contrib.auth.models import User
from django.db import models


class Project(models.Model):
    """
    A single project object
    """
    # requested user
    request_user = models.ForeignKey(User, on_delete=models.CASCADE, default=0)

    date_requested = models.DateTimeField()

    estimated_date_of_completion = models.DateTimeField(blank=True, null=True)

    milestones = models.ManyToManyField('Milestone', related_name='project_milestones', blank=True)

    project_name = models.CharField(max_length=10000)

    def __str__(self):
        """
        the string representation of this model
        """
        return f'{self.project_name} requested by: {self.request_user.username}'


class Milestone(models.Model):
    """
    Milestone
    """
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    milestone_name = models.CharField(max_length=1000)
    features = models.ManyToManyField('Feature', related_name='features', blank=True)

    def __str__(self):
        """
        the string representation of this model
        """
        return f'{self.milestone_name} is a part of: {self.project.project_name}'


class Feature(models.Model):
    """
    Feature
    """
    milestone = models.ForeignKey(Milestone, on_delete=models.CASCADE)
    feature_name = models.CharField(max_length=1000)
    completed = models.BooleanField(default=False)

    def __str__(self):
        """
        the string representation of this model
        """
        return f'{self.feature_name} is a part of: {self.milestone.milestone_name}'

dashboard/forms.py
from django import forms
from django.forms import Select

from .models import *


class ProjectCreationForm(forms.ModelForm):
    """
    Form for creating a new project
    """

    requesting_user = forms.ChoiceField(
        choices=[(u.id, u.username) for u in User.objects.filter(is_superuser=False).all()]
    )

    project_name = forms.CharField(
        widget=forms.TextInput()
    )

    class Meta:
        model = Project
        fields = ('requesting_user','project_name')
        widgets = {
            'users': Select(attrs={'class': 'select'})
        }

dashboard/views.py
from django.shortcuts import redirect
from django.shortcuts import render
from django.views import View

from dashboard.progress.project_handlers import get_project
from dashboard.requests.dashboard_requests import get_request


class IndexView(View):
    """
    Main view
    """
    template_name = 'dashboard/pages/dashboard.html'

    def get(self, request, *args, **kwargs):
        """
        Processes the get request for the main page.
        """
        if not request.user.is_authenticated:
            return redirect('auth:login')
        if request.user.is_superuser:
            return redirect('controller:index')
        return render(request, self.template_name, get_request(request))


def view_progress(request, p_client):
    """
    View progress view
    """

    # if request.user.is_superuser:
    #     return redirect(reverse('controller:update_progress', args=[project_client]))

    context = {
        'title': 'RYU | Project Details',
        'project': get_project(p_client)

    }

    return render(request, 'dashboard/pages/progress-view.html', context)

templates/dashboard/components/navbar.html
<nav class="navbar navbar-dark navbar-expand-md fixed-top bg-dark navigation-clean">
    <div class="container-fluid"><a class="navbar-brand" href="{% url 'main:index' %}">RYU&nbsp;</a>
        <button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span
                class="navbar-toggler-icon"></span></button>
        <div
                class="collapse navbar-collapse" id="navcol-1">
            <ul class="nav navbar-nav ml-auto">
                <li class="nav-item" role="presentation"><a class="nav-link {{ dashboard }}" href="{% url 'main:index' %}">Home</a></li>
                <li class="nav-item dropdown"><a class="dropdown-toggle nav-link" data-toggle="dropdown"
                                                 aria-expanded="false" href="#">My Account</a>
                    <div class="dropdown-menu" role="menu">
                        <a class="dropdown-item" role="presentation" href="{% url 'auth:logout' %}">Logout</a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>